/// Flutter icons NeumorphicIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NeumorphicIcons
///      fonts:
///       - asset: fonts/NeumorphicIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class NeumorphicIcons {
  NeumorphicIcons._();

  static const _kFontFam = 'NeumorphicIcons';
  static const _kFontPkg = "flutter_neumorphic";

  static const IconData check =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
